// interactive: true → user must click the highlighted element to advance (no "Next" button)
// interactive: false → informational step, shows "Next" button
// actionHint: shown in the interactive/drag CTA area — use specific element names

const STEPS_ZH = [
  {
    id: 'welcome',
    targetId: null,
    title: '歡迎使用 TripTogether！✈️',
    body: '嗨！我是你的旅行嚮導。接下來我會帶你認識所有功能——我們特別準備了一個「台北一日遊教學範例」，讓你邊操作邊學習！',
    interactive: false,
  },
  {
    id: 'create-trip',
    targetId: 'create-trip-btn',
    title: '建立旅遊計畫',
    body: '點擊「＋ 建立計畫」可以建立你的第一個旅行！設定旅行名稱、出發與返回日期，以及邀請朋友用的密碼。\n\n建立後系統會自動加入範例卡片，方便了解各種功能！',
    interactive: false,
    navHint: '請先回到首頁',
  },
  {
    id: 'join-trip',
    targetId: 'join-trip-btn',
    title: '加入朋友的計畫',
    body: '已有計畫代碼？輸入代碼，就可以共同規劃旅行。多人即時協作，更改一目了然！',
    interactive: false,
    navHint: '請先回到首頁',
  },
  {
    id: 'trip-card',
    targetId: 'first-trip-card',
    title: '點擊進入行程看板 👆',
    body: '這是「台北一日遊教學範例」計劃。點擊卡片進入行程看板，開始探索所有功能！',
    interactive: true,
    actionHint: '👆 點擊「台北一日遊教學範例」行程卡片',
    navHint: '請先回到首頁，點擊教學範例計劃',
  },
  {
    id: 'board-overview',
    targetId: 'overview-tab',
    title: '總覽頁面 👆',
    body: '「總覽」標籤整合了行程地圖、即時天氣、所有行程摘要，讓你一眼掌握旅行全貌！\n\n點擊「總覽」標籤切換到總覽畫面。',
    interactive: true,
    actionHint: '👆 點擊「總覽」標籤',
    navHint: '請先進入教學範例計劃',
  },
  {
    id: 'day-map',
    targetId: 'day-map-section',
    title: '今日行程地圖 🗺️',
    body: '搜尋地點新增的行程卡片，座標會自動顯示在這張地圖上，並用箭頭線串連成完整路線！',
    interactive: false,
    navHint: '請先進入教學範例計劃的總覽頁',
  },
  {
    id: 'weather',
    targetId: 'weather-pill',
    title: '即時天氣 ⛅',
    body: '根據行程地點自動查詢當地即時氣候。溫度、風速、天氣狀況一目了然！',
    interactive: false,
    navHint: '請先進入教學範例計劃的總覽頁',
  },
  {
    id: 'day-tab',
    targetId: 'day-1-tab',
    title: '單日時間軸 👆',
    body: '點擊日期標籤切換到單日視圖！以時間軸方式展示一天的行程，清楚看到每個景點的時間安排。',
    interactive: true,
    actionHint: '👆 點擊「Day 1」日期標籤',
    navHint: '請先進入教學範例計劃',
  },
  {
    id: 'add-card',
    targetId: 'add-card-fab',
    title: '新增行程卡片 ＋',
    body: '點擊右下角按鈕「＋」新增行程！支援景點、餐廳、住宿、交通、消費五種類型。\n\n📎 交通類型可以上傳機票、車票等附件！\n🔍 搜尋地點時會自動帶入地址和座標，同步顯示在地圖上。',
    interactive: false,
    navHint: '請切換到單日視圖',
  },
  {
    id: 'drag-drop',
    targetId: 'drag-card',
    title: '拖曳調整時間 ✋',
    body: '長按高亮的行程卡片左側握把，拖曳到下方空白時間格，就能快速調整行程順序！',
    interactive: false,
    requireDrag: true,
    actionHint: '長按行程拖曳到下方空白處',
    navHint: '請先點擊日期標籤切換到單日視圖',
  },
  {
    id: 'export-pdf',
    targetId: 'export-pdf-btn',
    title: '匯出 PDF 📄',
    body: '設定選單的「匯出 PDF」可以將完整行程輸出成 PDF 檔案，方便離線閱覽、列印或分享給朋友！',
    interactive: false,
    navHint: '功能位於設定選單裡面',
  },
  {
    id: 'todo',
    targetId: 'todo-btn',
    title: '待辦清單 ✅',
    body: '「待辦」可以管理出發前要準備的事項，勾選後顯示完成進度。',
    interactive: false,
    navHint: '請先進入教學範例計劃',
  },
  {
    id: 'packing',
    targetId: 'packing-btn',
    title: '打包清單 🎒',
    body: '「打包」清單幫你確認行李是否帶齊！逐一勾選確保行李齊全，再也不怕忘東忘西。',
    interactive: false,
    navHint: '請先進入教學範例計劃',
  },
  {
    id: 'expense',
    targetId: 'expense-btn',
    title: '開銷記錄 💰',
    body: '「開銷」可查看所有消費明細！\n\n在行程中新增消費紀錄，可記錄門票、餐廳費用、交通費等各種開銷並選擇幣別。\n\n系統會自動按幣別統計旅行總花費，匯出 PDF 時也會附上完整開銷明細。',
    interactive: false,
    navHint: '請先進入教學範例計劃',
  },
  {
    id: 'invite-friends',
    targetId: 'settings-btn',
    title: '邀請朋友一起規劃 👥',
    body: 'TripTogether 的核心功能——多人即時共同編輯！\n\n點擊「⚙️ 設定」，選擇「🔗 邀請」，即可看到旅行代碼。\n\n將代碼分享給朋友，任何人的新增、修改、刪除，所有人立即同步分享！',
    interactive: false,
    navHint: '請先進入教學範例計劃',
  },
  {
    id: 'settings-btn',
    targetId: 'settings-btn',
    title: '計畫設定 ⚙️',
    body: '設定頁面也可以修改旅行名稱與日期、查看所有成員清單。\n\n如果之後想複習功能，也可以在這裡重新啟動教學！',
    interactive: false,
    navHint: '請先進入教學範例計劃',
  },
  {
    id: 'complete',
    targetId: null,
    title: '🎉 教學完成！',
    body: '太棒了！你已經了解所有基本功能。教學範例計劃會自動消失，現在開始規劃你自己的旅行吧！\n\n如果之後想複習，可以隨時在計畫設定中重新啟動教學。',
    interactive: false,
    finish: true,
  },
]

const STEPS_EN = [
  {
    id: 'welcome',
    targetId: null,
    title: 'Welcome to TripTogether! ✈️',
    body: 'Hi! I\'m your travel guide. I\'ll walk you through all the features using a "Tokyo 1-Day Tour" demo trip — learn by doing!',
    interactive: false,
  },
  {
    id: 'create-trip',
    targetId: 'create-trip-btn',
    title: 'Create a Trip',
    body: 'Tap "+ Create Trip" to start your first journey! Set a trip name, start and end dates, and a join code for friends.\n\nSample cards are added automatically so you can explore all features!',
    interactive: false,
    navHint: 'Please go back to the Home page first',
  },
  {
    id: 'join-trip',
    targetId: 'join-trip-btn',
    title: 'Join a Friend\'s Trip',
    body: 'Have a trip code? Enter it to join a shared trip. Everyone sees edits in real time — no more messy group chats!',
    interactive: false,
    navHint: 'Please go back to the Home page first',
  },
  {
    id: 'trip-card',
    targetId: 'first-trip-card',
    title: 'Open the Trip Board 👆',
    body: 'This is the "Tokyo 1-Day Tour (Tutorial)" demo trip. Tap the card to enter the trip board and explore all features!',
    interactive: true,
    actionHint: '👆 Tap the "Tokyo 1-Day Tour (Tutorial)" trip card',
    navHint: 'Please go back to the Home page and tap the demo trip card',
  },
  {
    id: 'board-overview',
    targetId: 'overview-tab',
    title: 'Overview Tab 👆',
    body: 'The "Overview" tab shows the day map, live weather, and a summary of all your cards — everything at a glance!\n\nTap "Overview" to switch to the overview screen.',
    interactive: true,
    actionHint: '👆 Tap the "Overview" tab',
    navHint: 'Please enter the demo trip first',
  },
  {
    id: 'day-map',
    targetId: 'day-map-section',
    title: 'Day Route Map 🗺️',
    body: 'Cards with a location show up on this map, connected by arrows to form your complete daily route!',
    interactive: false,
    navHint: 'Please open the Overview tab of the demo trip',
  },
  {
    id: 'weather',
    targetId: 'weather-pill',
    title: 'Live Weather ⛅',
    body: 'Weather is fetched automatically based on your trip location. Temperature, wind, and conditions — all in one pill!',
    interactive: false,
    navHint: 'Please open the Overview tab of the demo trip',
  },
  {
    id: 'day-tab',
    targetId: 'day-1-tab',
    title: 'Day Timeline 👆',
    body: 'Tap a date tab to switch to the single-day view! The timeline shows all cards for that day in chronological order.',
    interactive: true,
    actionHint: '👆 Tap the "Day 1" date tab',
    navHint: 'Please enter the demo trip first',
  },
  {
    id: 'add-card',
    targetId: 'add-card-fab',
    title: 'Add Cards ＋',
    body: 'Tap the "＋" button to add a new card! Supports attractions, restaurants, accommodation, transport, and expenses.\n\n📎 Transport cards support ticket attachments!\n🔍 Place search auto-fills address and coordinates.',
    interactive: false,
    navHint: 'Please switch to the single-day view first',
  },
  {
    id: 'drag-drop',
    targetId: 'drag-card',
    title: 'Drag to Reschedule ✋',
    body: 'Long-press the left handle of the highlighted card, then drag it to a different time slot to reschedule!',
    interactive: false,
    requireDrag: true,
    actionHint: 'Long-press the card to drag it to a new time slot',
    navHint: 'Please tap a date tab to switch to the single-day view first',
  },
  {
    id: 'export-pdf',
    targetId: 'export-pdf-btn',
    title: 'Export PDF 📄',
    body: '"Export PDF" in the Settings menu generates a full itinerary PDF — perfect for offline viewing, printing, or sharing!',
    interactive: false,
    navHint: 'This feature is inside the Settings menu',
  },
  {
    id: 'todo',
    targetId: 'todo-btn',
    title: 'To-Do List ✅',
    body: '"To-Do" helps you manage pre-trip tasks. Check them off to track your progress!',
    interactive: false,
    navHint: 'Please enter the demo trip first',
  },
  {
    id: 'packing',
    targetId: 'packing-btn',
    title: 'Packing List 🎒',
    body: 'The packing list ensures you never forget anything! Check them off before departure.',
    interactive: false,
    navHint: 'Please enter the demo trip first',
  },
  {
    id: 'expense',
    targetId: 'expense-btn',
    title: 'Expense Tracking 💰',
    body: '"Expenses" shows all spending details!\n\nAdd expense cards for tickets, meals, transport, and more — choose any currency. The app tallies totals per currency and includes expenses in your PDF export.',
    interactive: false,
    navHint: 'Please enter the demo trip first',
  },
  {
    id: 'invite-friends',
    targetId: 'settings-btn',
    title: 'Invite Friends 👥',
    body: 'Real-time collaboration is TripTogether\'s core feature!\n\nTap "⚙️ Settings" → "🔗 Invite" to see the trip code.\n\nShare it with friends — everyone\'s additions, edits, and deletions appear instantly for all members!',
    interactive: false,
    navHint: 'Please enter the demo trip first',
  },
  {
    id: 'settings-btn',
    targetId: 'settings-btn',
    title: 'Trip Settings ⚙️',
    body: 'Settings also lets you edit the trip name and dates, and view all members.\n\nWant to replay the tutorial later? You can restart it from here anytime!',
    interactive: false,
    navHint: 'Please enter the demo trip first',
  },
  {
    id: 'complete',
    targetId: null,
    title: '🎉 Tutorial Complete!',
    body: 'Awesome! You now know all the core features. The demo trip will disappear automatically — time to plan your own adventure!\n\nWant a refresher? Restart the tutorial anytime from Trip Settings.',
    interactive: false,
    finish: true,
  },
]

export function getTutorialSteps(lang) {
  return lang === 'en' ? STEPS_EN : STEPS_ZH
}

// Legacy export for components that only need the count
export const TUTORIAL_STEPS = STEPS_ZH
